sudo: required

language: bash

services: docker

before_install:
  - docker build -t comp490-group3/api .
  - docker run -d -p 80:5000 comp490-group3/api
  - docker ps -a

script:
  - curl -i localhost