language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- true
deploy:
  provider: heroku
  api_key:
    secure: je0wQsJ9vwZlvwP8xNgoYLavlff8UOYVxdrUdi6EKsc17dlkRw5wXkg2jskFSGHimfi4cbc6EEAh+nNw66Mrzz/QsFgY8XDsYarLOg9Ru2Il82im3Gk6Nd+7VxYz2JGncBSMJwq6a0sXqX4/MMqjAVCIVtPNWE/OOX7dBkftLZxSIpey9TZ8qYEqsK0tVJRO8U4SE/8H2BhYYHKSyZ9GPeza3xUNWh5rNVXtF+yHPOaF3RaR40AF94kjk3LfdNBAI9JRw4rZCsdll3UUKLdIv1MBCiBE27xdqjGhtVQUrQ3eCQ1PQG2rnETjqV+kvnwYK977XBw+4duZ1SSMq9HwX8PP2vMqwAkfgioVXVI7h9dL0JkBq+BzZLaRmsWKvUPG73d2NkV+zjW1WTdSvnmfPgMotBVKiewz83p83VWwZGMTkVI8WL8awL1huiR4gLuBZZ5+oNF7R4AH7nWtEUXRNITBzpTVS0xsNsFGVTaUAiH+PoqgaYTPjCi0qWfWvgiVn25a5ZWDdpYnBLcbx7H9tuLD73VDXvRT9Eh/RHnUXQSXBIazCQi/h9hAM+K+gBQefHXGBt1w6FQC4jI8gsjDh2Hrtm/2G5zSuoa4NrcP6SqnYTZLMIAUiT1TKC9Nof98MZT2M54zCsLI7BwJJnffx52Wozm7tBvU07zxVsY2gw4=
  app: punchd
  on:
    repo: comp490-group3/backend-api
